//! A recording mock [`Fs`] that forwards every call to a wrapped FS.
//!
//! 1:1 port of Go `internal/vfs/vfsmock` (`wrapper.go` + the moq-generated
//! `FSMock`).
//!
//! DIVERGENCE(port): Go's `FSMock` is generated by `moq` with per-method `Func`
//! fields and a `reflect`-based `TestWrap`. Here `FsMock` always delegates to an
//! inner FS and records each call in a mutex-guarded vector, so the "all fields
//! wired" invariant holds by construction.

use std::sync::Mutex;
use std::time::SystemTime;

use crate::{Entries, FileInfo, Fs, FsResult, WalkDirFunc};

/// A recorded `write_file`/`append_file` call.
///
/// # Examples
/// ```
/// use tsgo_vfs::vfsmock::WriteFileCall;
/// let c = WriteFileCall { path: "/a".into(), data: "x".into() };
/// assert_eq!(c.path, "/a");
/// ```
///
/// Side effects: none (pure value type).
#[derive(Clone, Debug)]
pub struct WriteFileCall {
    /// The path argument.
    pub path: String,
    /// The data argument.
    pub data: String,
}

/// A mock `Fs` that records calls and forwards them to an inner FS.
///
/// # Examples
/// ```
/// use tsgo_vfs::Fs;
/// use tsgo_vfs::vfsmock::FsMock;
/// use tsgo_vfs::vfstest::MapFs;
/// let mock = FsMock::wrap(MapFs::from_map([("/a.ts", "x")], true));
/// assert!(mock.file_exists("/a.ts"));
/// assert_eq!(mock.file_exists_call_count(), 1);
/// ```
///
/// Side effects: records calls; forwards side effects to the inner FS.
// Go: internal/vfs/vfsmock/mock_generated.go:FSMock
pub struct FsMock {
    inner: Box<dyn Fs + Send + Sync>,
    directory_exists_calls: Mutex<Vec<String>>,
    file_exists_calls: Mutex<Vec<String>>,
    get_accessible_entries_calls: Mutex<Vec<String>>,
    read_file_calls: Mutex<Vec<String>>,
    realpath_calls: Mutex<Vec<String>>,
    remove_calls: Mutex<Vec<String>>,
    chtimes_calls: Mutex<Vec<String>>,
    stat_calls: Mutex<Vec<String>>,
    use_case_calls: Mutex<usize>,
    walk_dir_calls: Mutex<Vec<String>>,
    write_file_calls: Mutex<Vec<WriteFileCall>>,
    append_file_calls: Mutex<Vec<WriteFileCall>>,
}

impl FsMock {
    /// Wraps `inner`, forwarding all calls to it while recording them.
    ///
    /// Side effects: none at construction.
    // Go: internal/vfs/vfsmock/wrapper.go:Wrap
    pub fn wrap<F: Fs + Send + Sync + 'static>(inner: F) -> Self {
        FsMock {
            inner: Box::new(inner),
            directory_exists_calls: Mutex::new(Vec::new()),
            file_exists_calls: Mutex::new(Vec::new()),
            get_accessible_entries_calls: Mutex::new(Vec::new()),
            read_file_calls: Mutex::new(Vec::new()),
            realpath_calls: Mutex::new(Vec::new()),
            remove_calls: Mutex::new(Vec::new()),
            chtimes_calls: Mutex::new(Vec::new()),
            stat_calls: Mutex::new(Vec::new()),
            use_case_calls: Mutex::new(0),
            walk_dir_calls: Mutex::new(Vec::new()),
            write_file_calls: Mutex::new(Vec::new()),
            append_file_calls: Mutex::new(Vec::new()),
        }
    }

    /// Number of `directory_exists` calls recorded.
    ///
    /// Side effects: none.
    pub fn directory_exists_call_count(&self) -> usize {
        self.directory_exists_calls.lock().unwrap().len()
    }

    /// Number of `file_exists` calls recorded.
    ///
    /// Side effects: none.
    pub fn file_exists_call_count(&self) -> usize {
        self.file_exists_calls.lock().unwrap().len()
    }

    /// Number of `get_accessible_entries` calls recorded.
    ///
    /// Side effects: none.
    pub fn get_accessible_entries_call_count(&self) -> usize {
        self.get_accessible_entries_calls.lock().unwrap().len()
    }

    /// Number of `read_file` calls recorded.
    ///
    /// Side effects: none.
    pub fn read_file_call_count(&self) -> usize {
        self.read_file_calls.lock().unwrap().len()
    }

    /// Number of `realpath` calls recorded.
    ///
    /// Side effects: none.
    pub fn realpath_call_count(&self) -> usize {
        self.realpath_calls.lock().unwrap().len()
    }

    /// Number of `remove` calls recorded.
    ///
    /// Side effects: none.
    pub fn remove_call_count(&self) -> usize {
        self.remove_calls.lock().unwrap().len()
    }

    /// Number of `chtimes` calls recorded.
    ///
    /// Side effects: none.
    pub fn chtimes_call_count(&self) -> usize {
        self.chtimes_calls.lock().unwrap().len()
    }

    /// Number of `stat` calls recorded.
    ///
    /// Side effects: none.
    pub fn stat_call_count(&self) -> usize {
        self.stat_calls.lock().unwrap().len()
    }

    /// Number of `use_case_sensitive_file_names` calls recorded.
    ///
    /// Side effects: none.
    pub fn use_case_sensitive_file_names_call_count(&self) -> usize {
        *self.use_case_calls.lock().unwrap()
    }

    /// Number of `walk_dir` calls recorded.
    ///
    /// Side effects: none.
    pub fn walk_dir_call_count(&self) -> usize {
        self.walk_dir_calls.lock().unwrap().len()
    }

    /// The recorded `write_file` calls.
    ///
    /// Side effects: none.
    pub fn write_file_calls(&self) -> Vec<WriteFileCall> {
        self.write_file_calls.lock().unwrap().clone()
    }

    /// The recorded `append_file` calls.
    ///
    /// Side effects: none.
    pub fn append_file_calls(&self) -> Vec<WriteFileCall> {
        self.append_file_calls.lock().unwrap().clone()
    }
}

impl Fs for FsMock {
    fn use_case_sensitive_file_names(&self) -> bool {
        *self.use_case_calls.lock().unwrap() += 1;
        self.inner.use_case_sensitive_file_names()
    }

    fn file_exists(&self, path: &str) -> bool {
        self.file_exists_calls
            .lock()
            .unwrap()
            .push(path.to_string());
        self.inner.file_exists(path)
    }

    fn read_file(&self, path: &str) -> Option<String> {
        self.read_file_calls.lock().unwrap().push(path.to_string());
        self.inner.read_file(path)
    }

    fn write_file(&self, path: &str, data: &str) -> FsResult<()> {
        self.write_file_calls.lock().unwrap().push(WriteFileCall {
            path: path.to_string(),
            data: data.to_string(),
        });
        self.inner.write_file(path, data)
    }

    fn append_file(&self, path: &str, data: &str) -> FsResult<()> {
        self.append_file_calls.lock().unwrap().push(WriteFileCall {
            path: path.to_string(),
            data: data.to_string(),
        });
        self.inner.append_file(path, data)
    }

    fn remove(&self, path: &str) -> FsResult<()> {
        self.remove_calls.lock().unwrap().push(path.to_string());
        self.inner.remove(path)
    }

    fn chtimes(&self, path: &str, atime: SystemTime, mtime: SystemTime) -> FsResult<()> {
        self.chtimes_calls.lock().unwrap().push(path.to_string());
        self.inner.chtimes(path, atime, mtime)
    }

    fn directory_exists(&self, path: &str) -> bool {
        self.directory_exists_calls
            .lock()
            .unwrap()
            .push(path.to_string());
        self.inner.directory_exists(path)
    }

    fn get_accessible_entries(&self, path: &str) -> Entries {
        self.get_accessible_entries_calls
            .lock()
            .unwrap()
            .push(path.to_string());
        self.inner.get_accessible_entries(path)
    }

    fn stat(&self, path: &str) -> Option<FileInfo> {
        self.stat_calls.lock().unwrap().push(path.to_string());
        self.inner.stat(path)
    }

    fn walk_dir(&self, root: &str, walk_fn: &mut WalkDirFunc) -> FsResult<()> {
        self.walk_dir_calls.lock().unwrap().push(root.to_string());
        self.inner.walk_dir(root, walk_fn)
    }

    fn realpath(&self, path: &str) -> String {
        self.realpath_calls.lock().unwrap().push(path.to_string());
        self.inner.realpath(path)
    }
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
