// Code generated from Go `internal/ast/kind_generated.go`. DO NOT EDIT BY HAND.
//! Syntax-tree node kinds (`Kind`) and their range constants.
//!
//! 1:1 port of Go `internal/ast/kind_generated.go` (a generated file). The
//! discriminants match Go exactly; `Display` reproduces the Go `stringer` names.

#![allow(missing_docs)]

/// A syntax-tree node kind.
///
/// Mirrors Go `Kind` (an `int16` `iota` enum). Many kinds share a single
/// `NodeData` variant (e.g. all punctuation/keyword tokens), so `Kind` is kept
/// separate from the data payload.
///
/// # Examples
/// ```
/// use tsgo_ast::kind_generated::Kind;
/// assert_eq!(Kind::Unknown as i16, 0);
/// assert_eq!(Kind::Count as i16, 351);
/// ```
///
/// Side effects: none (pure value type).
// Go: internal/ast/kind_generated.go:Kind
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord)]
#[repr(i16)]
pub enum Kind {
    Unknown = 0,
    EndOfFile,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,
    NewLineTrivia,
    WhitespaceTrivia,
    ConflictMarkerTrivia,
    NonTextFileMarkerTrivia,
    NumericLiteral,
    BigIntLiteral,
    StringLiteral,
    JsxText,
    JsxTextAllWhiteSpaces,
    RegularExpressionLiteral,
    NoSubstitutionTemplateLiteral,
    TemplateHead,
    TemplateMiddle,
    TemplateTail,
    OpenBraceToken,
    CloseBraceToken,
    OpenParenToken,
    CloseParenToken,
    OpenBracketToken,
    CloseBracketToken,
    DotToken,
    DotDotDotToken,
    SemicolonToken,
    CommaToken,
    QuestionDotToken,
    LessThanToken,
    LessThanSlashToken,
    GreaterThanToken,
    LessThanEqualsToken,
    GreaterThanEqualsToken,
    EqualsEqualsToken,
    ExclamationEqualsToken,
    EqualsEqualsEqualsToken,
    ExclamationEqualsEqualsToken,
    EqualsGreaterThanToken,
    PlusToken,
    MinusToken,
    AsteriskToken,
    AsteriskAsteriskToken,
    SlashToken,
    PercentToken,
    PlusPlusToken,
    MinusMinusToken,
    LessThanLessThanToken,
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanGreaterThanToken,
    AmpersandToken,
    BarToken,
    CaretToken,
    ExclamationToken,
    TildeToken,
    AmpersandAmpersandToken,
    BarBarToken,
    QuestionToken,
    ColonToken,
    AtToken,
    QuestionQuestionToken,
    BacktickToken,
    HashToken,
    EqualsToken,
    PlusEqualsToken,
    MinusEqualsToken,
    AsteriskEqualsToken,
    AsteriskAsteriskEqualsToken,
    SlashEqualsToken,
    PercentEqualsToken,
    LessThanLessThanEqualsToken,
    GreaterThanGreaterThanEqualsToken,
    GreaterThanGreaterThanGreaterThanEqualsToken,
    AmpersandEqualsToken,
    BarEqualsToken,
    BarBarEqualsToken,
    AmpersandAmpersandEqualsToken,
    QuestionQuestionEqualsToken,
    CaretEqualsToken,
    Identifier,
    PrivateIdentifier,
    JSDocCommentTextToken,
    BreakKeyword,
    CaseKeyword,
    CatchKeyword,
    ClassKeyword,
    ConstKeyword,
    ContinueKeyword,
    DebuggerKeyword,
    DefaultKeyword,
    DeleteKeyword,
    DoKeyword,
    ElseKeyword,
    EnumKeyword,
    ExportKeyword,
    ExtendsKeyword,
    FalseKeyword,
    FinallyKeyword,
    ForKeyword,
    FunctionKeyword,
    IfKeyword,
    ImportKeyword,
    InKeyword,
    InstanceOfKeyword,
    NewKeyword,
    NullKeyword,
    ReturnKeyword,
    SuperKeyword,
    SwitchKeyword,
    ThisKeyword,
    ThrowKeyword,
    TrueKeyword,
    TryKeyword,
    TypeOfKeyword,
    VarKeyword,
    VoidKeyword,
    WhileKeyword,
    WithKeyword,
    ImplementsKeyword,
    InterfaceKeyword,
    LetKeyword,
    PackageKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    PublicKeyword,
    StaticKeyword,
    YieldKeyword,
    AbstractKeyword,
    AccessorKeyword,
    AsKeyword,
    AssertsKeyword,
    AssertKeyword,
    AnyKeyword,
    AsyncKeyword,
    AwaitKeyword,
    BooleanKeyword,
    ConstructorKeyword,
    DeclareKeyword,
    GetKeyword,
    ImmediateKeyword,
    InferKeyword,
    IntrinsicKeyword,
    IsKeyword,
    KeyOfKeyword,
    ModuleKeyword,
    NamespaceKeyword,
    NeverKeyword,
    OutKeyword,
    ReadonlyKeyword,
    RequireKeyword,
    NumberKeyword,
    ObjectKeyword,
    SatisfiesKeyword,
    SetKeyword,
    StringKeyword,
    SymbolKeyword,
    TypeKeyword,
    UndefinedKeyword,
    UniqueKeyword,
    UnknownKeyword,
    UsingKeyword,
    FromKeyword,
    GlobalKeyword,
    BigIntKeyword,
    OverrideKeyword,
    OfKeyword,
    DeferKeyword,
    QualifiedName,
    ComputedPropertyName,
    TypeParameter,
    Parameter,
    Decorator,
    PropertySignature,
    PropertyDeclaration,
    MethodSignature,
    MethodDeclaration,
    ClassStaticBlockDeclaration,
    Constructor,
    GetAccessor,
    SetAccessor,
    CallSignature,
    ConstructSignature,
    IndexSignature,
    TypePredicate,
    TypeReference,
    FunctionType,
    ConstructorType,
    TypeQuery,
    TypeLiteral,
    ArrayType,
    TupleType,
    OptionalType,
    RestType,
    UnionType,
    IntersectionType,
    ConditionalType,
    InferType,
    ParenthesizedType,
    ThisType,
    TypeOperator,
    IndexedAccessType,
    MappedType,
    LiteralType,
    NamedTupleMember,
    TemplateLiteralType,
    TemplateLiteralTypeSpan,
    ImportType,
    ObjectBindingPattern,
    ArrayBindingPattern,
    BindingElement,
    ArrayLiteralExpression,
    ObjectLiteralExpression,
    PropertyAccessExpression,
    ElementAccessExpression,
    CallExpression,
    NewExpression,
    TaggedTemplateExpression,
    TypeAssertionExpression,
    ParenthesizedExpression,
    FunctionExpression,
    ArrowFunction,
    DeleteExpression,
    TypeOfExpression,
    VoidExpression,
    AwaitExpression,
    PrefixUnaryExpression,
    PostfixUnaryExpression,
    BinaryExpression,
    ConditionalExpression,
    TemplateExpression,
    YieldExpression,
    SpreadElement,
    ClassExpression,
    OmittedExpression,
    ExpressionWithTypeArguments,
    AsExpression,
    NonNullExpression,
    MetaProperty,
    SyntheticExpression,
    SatisfiesExpression,
    TemplateSpan,
    SemicolonClassElement,
    Block,
    EmptyStatement,
    VariableStatement,
    ExpressionStatement,
    IfStatement,
    DoStatement,
    WhileStatement,
    ForStatement,
    ForInStatement,
    ForOfStatement,
    ContinueStatement,
    BreakStatement,
    ReturnStatement,
    WithStatement,
    SwitchStatement,
    LabeledStatement,
    ThrowStatement,
    TryStatement,
    DebuggerStatement,
    VariableDeclaration,
    VariableDeclarationList,
    FunctionDeclaration,
    ClassDeclaration,
    InterfaceDeclaration,
    TypeAliasDeclaration,
    EnumDeclaration,
    ModuleDeclaration,
    ModuleBlock,
    CaseBlock,
    NamespaceExportDeclaration,
    ImportEqualsDeclaration,
    ImportDeclaration,
    ImportClause,
    NamespaceImport,
    NamedImports,
    ImportSpecifier,
    ExportAssignment,
    ExportDeclaration,
    NamedExports,
    NamespaceExport,
    ExportSpecifier,
    MissingDeclaration,
    ExternalModuleReference,
    JsxElement,
    JsxSelfClosingElement,
    JsxOpeningElement,
    JsxClosingElement,
    JsxFragment,
    JsxOpeningFragment,
    JsxClosingFragment,
    JsxAttribute,
    JsxAttributes,
    JsxSpreadAttribute,
    JsxExpression,
    JsxNamespacedName,
    CaseClause,
    DefaultClause,
    HeritageClause,
    CatchClause,
    ImportAttributes,
    ImportAttribute,
    PropertyAssignment,
    ShorthandPropertyAssignment,
    SpreadAssignment,
    EnumMember,
    SourceFile,
    JSDocTypeExpression,
    JSDocNameReference,
    JSDocAllType,
    JSDocNullableType,
    JSDocNonNullableType,
    JSDocOptionalType,
    JSDocVariadicType,
    JSDoc,
    JSDocText,
    JSDocTypeLiteral,
    JSDocSignature,
    JSDocLink,
    JSDocLinkCode,
    JSDocLinkPlain,
    JSDocUnknownTag,
    JSDocAugmentsTag,
    JSDocImplementsTag,
    JSDocDeprecatedTag,
    JSDocPublicTag,
    JSDocPrivateTag,
    JSDocProtectedTag,
    JSDocReadonlyTag,
    JSDocOverrideTag,
    JSDocCallbackTag,
    JSDocOverloadTag,
    JSDocParameterTag,
    JSDocReturnTag,
    JSDocThisTag,
    JSDocTypeTag,
    JSDocTemplateTag,
    JSDocTypedefTag,
    JSDocSeeTag,
    JSDocPropertyTag,
    JSDocThrowsTag,
    JSDocSatisfiesTag,
    JSDocImportTag,
    SyntaxList,
    JSTypeAliasDeclaration,
    JSImportDeclaration,
    NotEmittedStatement,
    PartiallyEmittedExpression,
    SyntheticReferenceExpression,
    NotEmittedTypeElement,
    Count,
}

impl Kind {
    /// Go: `KindFirstAssignment = KindEqualsToken`.
    pub const FIRST_ASSIGNMENT: Kind = Kind::EqualsToken;
    /// Go: `KindLastAssignment = KindCaretEqualsToken`.
    pub const LAST_ASSIGNMENT: Kind = Kind::CaretEqualsToken;
    /// Go: `KindFirstCompoundAssignment = KindPlusEqualsToken`.
    pub const FIRST_COMPOUND_ASSIGNMENT: Kind = Kind::PlusEqualsToken;
    /// Go: `KindLastCompoundAssignment = KindCaretEqualsToken`.
    pub const LAST_COMPOUND_ASSIGNMENT: Kind = Kind::CaretEqualsToken;
    /// Go: `KindFirstReservedWord = KindBreakKeyword`.
    pub const FIRST_RESERVED_WORD: Kind = Kind::BreakKeyword;
    /// Go: `KindLastReservedWord = KindWithKeyword`.
    pub const LAST_RESERVED_WORD: Kind = Kind::WithKeyword;
    /// Go: `KindFirstKeyword = KindBreakKeyword`.
    pub const FIRST_KEYWORD: Kind = Kind::BreakKeyword;
    /// Go: `KindLastKeyword = KindDeferKeyword`.
    pub const LAST_KEYWORD: Kind = Kind::DeferKeyword;
    /// Go: `KindFirstFutureReservedWord = KindImplementsKeyword`.
    pub const FIRST_FUTURE_RESERVED_WORD: Kind = Kind::ImplementsKeyword;
    /// Go: `KindLastFutureReservedWord = KindYieldKeyword`.
    pub const LAST_FUTURE_RESERVED_WORD: Kind = Kind::YieldKeyword;
    /// Go: `KindFirstTypeNode = KindTypePredicate`.
    pub const FIRST_TYPE_NODE: Kind = Kind::TypePredicate;
    /// Go: `KindLastTypeNode = KindImportType`.
    pub const LAST_TYPE_NODE: Kind = Kind::ImportType;
    /// Go: `KindFirstPunctuation = KindOpenBraceToken`.
    pub const FIRST_PUNCTUATION: Kind = Kind::OpenBraceToken;
    /// Go: `KindLastPunctuation = KindCaretEqualsToken`.
    pub const LAST_PUNCTUATION: Kind = Kind::CaretEqualsToken;
    /// Go: `KindFirstToken = KindUnknown`.
    pub const FIRST_TOKEN: Kind = Kind::Unknown;
    /// Go: `KindLastToken = KindLastKeyword`.
    pub const LAST_TOKEN: Kind = Kind::LAST_KEYWORD;
    /// Go: `KindFirstLiteralToken = KindNumericLiteral`.
    pub const FIRST_LITERAL_TOKEN: Kind = Kind::NumericLiteral;
    /// Go: `KindLastLiteralToken = KindNoSubstitutionTemplateLiteral`.
    pub const LAST_LITERAL_TOKEN: Kind = Kind::NoSubstitutionTemplateLiteral;
    /// Go: `KindFirstTemplateToken = KindNoSubstitutionTemplateLiteral`.
    pub const FIRST_TEMPLATE_TOKEN: Kind = Kind::NoSubstitutionTemplateLiteral;
    /// Go: `KindLastTemplateToken = KindTemplateTail`.
    pub const LAST_TEMPLATE_TOKEN: Kind = Kind::TemplateTail;
    /// Go: `KindFirstBinaryOperator = KindLessThanToken`.
    pub const FIRST_BINARY_OPERATOR: Kind = Kind::LessThanToken;
    /// Go: `KindLastBinaryOperator = KindCaretEqualsToken`.
    pub const LAST_BINARY_OPERATOR: Kind = Kind::CaretEqualsToken;
    /// Go: `KindFirstStatement = KindVariableStatement`.
    pub const FIRST_STATEMENT: Kind = Kind::VariableStatement;
    /// Go: `KindLastStatement = KindDebuggerStatement`.
    pub const LAST_STATEMENT: Kind = Kind::DebuggerStatement;
    /// Go: `KindFirstNode = KindQualifiedName`.
    pub const FIRST_NODE: Kind = Kind::QualifiedName;
    /// Go: `KindFirstJSDocNode = KindJSDocTypeExpression`.
    pub const FIRST_J_S_DOC_NODE: Kind = Kind::JSDocTypeExpression;
    /// Go: `KindLastJSDocNode = KindJSDocImportTag`.
    pub const LAST_J_S_DOC_NODE: Kind = Kind::JSDocImportTag;
    /// Go: `KindFirstJSDocTagNode = KindJSDocUnknownTag`.
    pub const FIRST_J_S_DOC_TAG_NODE: Kind = Kind::JSDocUnknownTag;
    /// Go: `KindLastJSDocTagNode = KindJSDocImportTag`.
    pub const LAST_J_S_DOC_TAG_NODE: Kind = Kind::JSDocImportTag;
    /// Go: `KindFirstContextualKeyword = KindAbstractKeyword`.
    pub const FIRST_CONTEXTUAL_KEYWORD: Kind = Kind::AbstractKeyword;
    /// Go: `KindLastContextualKeyword = KindDeferKeyword`.
    pub const LAST_CONTEXTUAL_KEYWORD: Kind = Kind::DeferKeyword;
    /// Go: `KindLastUnaryOperator = KindTildeToken`.
    pub const LAST_UNARY_OPERATOR: Kind = Kind::TildeToken;
    /// Go: `KindFirstTriviaToken = KindSingleLineCommentTrivia`.
    pub const FIRST_TRIVIA_TOKEN: Kind = Kind::SingleLineCommentTrivia;
    /// Go: `KindLastTriviaToken = KindConflictMarkerTrivia`.
    pub const LAST_TRIVIA_TOKEN: Kind = Kind::ConflictMarkerTrivia;
}

const KIND_NAMES: [&str; 352] = [
    "KindUnknown",
    "KindEndOfFile",
    "KindSingleLineCommentTrivia",
    "KindMultiLineCommentTrivia",
    "KindNewLineTrivia",
    "KindWhitespaceTrivia",
    "KindConflictMarkerTrivia",
    "KindNonTextFileMarkerTrivia",
    "KindNumericLiteral",
    "KindBigIntLiteral",
    "KindStringLiteral",
    "KindJsxText",
    "KindJsxTextAllWhiteSpaces",
    "KindRegularExpressionLiteral",
    "KindNoSubstitutionTemplateLiteral",
    "KindTemplateHead",
    "KindTemplateMiddle",
    "KindTemplateTail",
    "KindOpenBraceToken",
    "KindCloseBraceToken",
    "KindOpenParenToken",
    "KindCloseParenToken",
    "KindOpenBracketToken",
    "KindCloseBracketToken",
    "KindDotToken",
    "KindDotDotDotToken",
    "KindSemicolonToken",
    "KindCommaToken",
    "KindQuestionDotToken",
    "KindLessThanToken",
    "KindLessThanSlashToken",
    "KindGreaterThanToken",
    "KindLessThanEqualsToken",
    "KindGreaterThanEqualsToken",
    "KindEqualsEqualsToken",
    "KindExclamationEqualsToken",
    "KindEqualsEqualsEqualsToken",
    "KindExclamationEqualsEqualsToken",
    "KindEqualsGreaterThanToken",
    "KindPlusToken",
    "KindMinusToken",
    "KindAsteriskToken",
    "KindAsteriskAsteriskToken",
    "KindSlashToken",
    "KindPercentToken",
    "KindPlusPlusToken",
    "KindMinusMinusToken",
    "KindLessThanLessThanToken",
    "KindGreaterThanGreaterThanToken",
    "KindGreaterThanGreaterThanGreaterThanToken",
    "KindAmpersandToken",
    "KindBarToken",
    "KindCaretToken",
    "KindExclamationToken",
    "KindTildeToken",
    "KindAmpersandAmpersandToken",
    "KindBarBarToken",
    "KindQuestionToken",
    "KindColonToken",
    "KindAtToken",
    "KindQuestionQuestionToken",
    "KindBacktickToken",
    "KindHashToken",
    "KindEqualsToken",
    "KindPlusEqualsToken",
    "KindMinusEqualsToken",
    "KindAsteriskEqualsToken",
    "KindAsteriskAsteriskEqualsToken",
    "KindSlashEqualsToken",
    "KindPercentEqualsToken",
    "KindLessThanLessThanEqualsToken",
    "KindGreaterThanGreaterThanEqualsToken",
    "KindGreaterThanGreaterThanGreaterThanEqualsToken",
    "KindAmpersandEqualsToken",
    "KindBarEqualsToken",
    "KindBarBarEqualsToken",
    "KindAmpersandAmpersandEqualsToken",
    "KindQuestionQuestionEqualsToken",
    "KindCaretEqualsToken",
    "KindIdentifier",
    "KindPrivateIdentifier",
    "KindJSDocCommentTextToken",
    "KindBreakKeyword",
    "KindCaseKeyword",
    "KindCatchKeyword",
    "KindClassKeyword",
    "KindConstKeyword",
    "KindContinueKeyword",
    "KindDebuggerKeyword",
    "KindDefaultKeyword",
    "KindDeleteKeyword",
    "KindDoKeyword",
    "KindElseKeyword",
    "KindEnumKeyword",
    "KindExportKeyword",
    "KindExtendsKeyword",
    "KindFalseKeyword",
    "KindFinallyKeyword",
    "KindForKeyword",
    "KindFunctionKeyword",
    "KindIfKeyword",
    "KindImportKeyword",
    "KindInKeyword",
    "KindInstanceOfKeyword",
    "KindNewKeyword",
    "KindNullKeyword",
    "KindReturnKeyword",
    "KindSuperKeyword",
    "KindSwitchKeyword",
    "KindThisKeyword",
    "KindThrowKeyword",
    "KindTrueKeyword",
    "KindTryKeyword",
    "KindTypeOfKeyword",
    "KindVarKeyword",
    "KindVoidKeyword",
    "KindWhileKeyword",
    "KindWithKeyword",
    "KindImplementsKeyword",
    "KindInterfaceKeyword",
    "KindLetKeyword",
    "KindPackageKeyword",
    "KindPrivateKeyword",
    "KindProtectedKeyword",
    "KindPublicKeyword",
    "KindStaticKeyword",
    "KindYieldKeyword",
    "KindAbstractKeyword",
    "KindAccessorKeyword",
    "KindAsKeyword",
    "KindAssertsKeyword",
    "KindAssertKeyword",
    "KindAnyKeyword",
    "KindAsyncKeyword",
    "KindAwaitKeyword",
    "KindBooleanKeyword",
    "KindConstructorKeyword",
    "KindDeclareKeyword",
    "KindGetKeyword",
    "KindImmediateKeyword",
    "KindInferKeyword",
    "KindIntrinsicKeyword",
    "KindIsKeyword",
    "KindKeyOfKeyword",
    "KindModuleKeyword",
    "KindNamespaceKeyword",
    "KindNeverKeyword",
    "KindOutKeyword",
    "KindReadonlyKeyword",
    "KindRequireKeyword",
    "KindNumberKeyword",
    "KindObjectKeyword",
    "KindSatisfiesKeyword",
    "KindSetKeyword",
    "KindStringKeyword",
    "KindSymbolKeyword",
    "KindTypeKeyword",
    "KindUndefinedKeyword",
    "KindUniqueKeyword",
    "KindUnknownKeyword",
    "KindUsingKeyword",
    "KindFromKeyword",
    "KindGlobalKeyword",
    "KindBigIntKeyword",
    "KindOverrideKeyword",
    "KindOfKeyword",
    "KindDeferKeyword",
    "KindQualifiedName",
    "KindComputedPropertyName",
    "KindTypeParameter",
    "KindParameter",
    "KindDecorator",
    "KindPropertySignature",
    "KindPropertyDeclaration",
    "KindMethodSignature",
    "KindMethodDeclaration",
    "KindClassStaticBlockDeclaration",
    "KindConstructor",
    "KindGetAccessor",
    "KindSetAccessor",
    "KindCallSignature",
    "KindConstructSignature",
    "KindIndexSignature",
    "KindTypePredicate",
    "KindTypeReference",
    "KindFunctionType",
    "KindConstructorType",
    "KindTypeQuery",
    "KindTypeLiteral",
    "KindArrayType",
    "KindTupleType",
    "KindOptionalType",
    "KindRestType",
    "KindUnionType",
    "KindIntersectionType",
    "KindConditionalType",
    "KindInferType",
    "KindParenthesizedType",
    "KindThisType",
    "KindTypeOperator",
    "KindIndexedAccessType",
    "KindMappedType",
    "KindLiteralType",
    "KindNamedTupleMember",
    "KindTemplateLiteralType",
    "KindTemplateLiteralTypeSpan",
    "KindImportType",
    "KindObjectBindingPattern",
    "KindArrayBindingPattern",
    "KindBindingElement",
    "KindArrayLiteralExpression",
    "KindObjectLiteralExpression",
    "KindPropertyAccessExpression",
    "KindElementAccessExpression",
    "KindCallExpression",
    "KindNewExpression",
    "KindTaggedTemplateExpression",
    "KindTypeAssertionExpression",
    "KindParenthesizedExpression",
    "KindFunctionExpression",
    "KindArrowFunction",
    "KindDeleteExpression",
    "KindTypeOfExpression",
    "KindVoidExpression",
    "KindAwaitExpression",
    "KindPrefixUnaryExpression",
    "KindPostfixUnaryExpression",
    "KindBinaryExpression",
    "KindConditionalExpression",
    "KindTemplateExpression",
    "KindYieldExpression",
    "KindSpreadElement",
    "KindClassExpression",
    "KindOmittedExpression",
    "KindExpressionWithTypeArguments",
    "KindAsExpression",
    "KindNonNullExpression",
    "KindMetaProperty",
    "KindSyntheticExpression",
    "KindSatisfiesExpression",
    "KindTemplateSpan",
    "KindSemicolonClassElement",
    "KindBlock",
    "KindEmptyStatement",
    "KindVariableStatement",
    "KindExpressionStatement",
    "KindIfStatement",
    "KindDoStatement",
    "KindWhileStatement",
    "KindForStatement",
    "KindForInStatement",
    "KindForOfStatement",
    "KindContinueStatement",
    "KindBreakStatement",
    "KindReturnStatement",
    "KindWithStatement",
    "KindSwitchStatement",
    "KindLabeledStatement",
    "KindThrowStatement",
    "KindTryStatement",
    "KindDebuggerStatement",
    "KindVariableDeclaration",
    "KindVariableDeclarationList",
    "KindFunctionDeclaration",
    "KindClassDeclaration",
    "KindInterfaceDeclaration",
    "KindTypeAliasDeclaration",
    "KindEnumDeclaration",
    "KindModuleDeclaration",
    "KindModuleBlock",
    "KindCaseBlock",
    "KindNamespaceExportDeclaration",
    "KindImportEqualsDeclaration",
    "KindImportDeclaration",
    "KindImportClause",
    "KindNamespaceImport",
    "KindNamedImports",
    "KindImportSpecifier",
    "KindExportAssignment",
    "KindExportDeclaration",
    "KindNamedExports",
    "KindNamespaceExport",
    "KindExportSpecifier",
    "KindMissingDeclaration",
    "KindExternalModuleReference",
    "KindJsxElement",
    "KindJsxSelfClosingElement",
    "KindJsxOpeningElement",
    "KindJsxClosingElement",
    "KindJsxFragment",
    "KindJsxOpeningFragment",
    "KindJsxClosingFragment",
    "KindJsxAttribute",
    "KindJsxAttributes",
    "KindJsxSpreadAttribute",
    "KindJsxExpression",
    "KindJsxNamespacedName",
    "KindCaseClause",
    "KindDefaultClause",
    "KindHeritageClause",
    "KindCatchClause",
    "KindImportAttributes",
    "KindImportAttribute",
    "KindPropertyAssignment",
    "KindShorthandPropertyAssignment",
    "KindSpreadAssignment",
    "KindEnumMember",
    "KindSourceFile",
    "KindJSDocTypeExpression",
    "KindJSDocNameReference",
    "KindJSDocAllType",
    "KindJSDocNullableType",
    "KindJSDocNonNullableType",
    "KindJSDocOptionalType",
    "KindJSDocVariadicType",
    "KindJSDoc",
    "KindJSDocText",
    "KindJSDocTypeLiteral",
    "KindJSDocSignature",
    "KindJSDocLink",
    "KindJSDocLinkCode",
    "KindJSDocLinkPlain",
    "KindJSDocUnknownTag",
    "KindJSDocAugmentsTag",
    "KindJSDocImplementsTag",
    "KindJSDocDeprecatedTag",
    "KindJSDocPublicTag",
    "KindJSDocPrivateTag",
    "KindJSDocProtectedTag",
    "KindJSDocReadonlyTag",
    "KindJSDocOverrideTag",
    "KindJSDocCallbackTag",
    "KindJSDocOverloadTag",
    "KindJSDocParameterTag",
    "KindJSDocReturnTag",
    "KindJSDocThisTag",
    "KindJSDocTypeTag",
    "KindJSDocTemplateTag",
    "KindJSDocTypedefTag",
    "KindJSDocSeeTag",
    "KindJSDocPropertyTag",
    "KindJSDocThrowsTag",
    "KindJSDocSatisfiesTag",
    "KindJSDocImportTag",
    "KindSyntaxList",
    "KindJSTypeAliasDeclaration",
    "KindJSImportDeclaration",
    "KindNotEmittedStatement",
    "KindPartiallyEmittedExpression",
    "KindSyntheticReferenceExpression",
    "KindNotEmittedTypeElement",
    "KindCount",
];

impl std::fmt::Display for Kind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let idx = *self as i16;
        if idx < 0 || idx as usize >= KIND_NAMES.len() {
            return write!(f, "Kind({idx})");
        }
        f.write_str(KIND_NAMES[idx as usize])
    }
}

#[cfg(test)]
#[path = "kind_generated_test.rs"]
mod tests;
