//! The full formatting rule table.
//!
//! 1:1 port of Go `internal/format/rules.go`: [`get_all_rules`] builds every
//! formatting rule (high-priority common, user-configurable, then low-priority
//! common), plus the token-range constructors.
//!
//! # `ALL_TOKEN_KINDS`
//!
//! Go iterates `for token := KindFirstToken; token <= KindLastToken; token++`.
//! The Rust `tsgo_ast::Kind` enum has no `i16 -> Kind` reverse map, so the token
//! range `[Unknown ..= DeferKeyword]` is materialized as the
//! [`ALL_TOKEN_KINDS`] table. A self-check test asserts the table is contiguous
//! and ends at `KindLastToken`, guarding against drift from `tsgo_ast`.

use crate::context::{any_context, ContextPredicate, FormattingContext};
use crate::rule::{rule, rule_flags, RuleSpec, TokenRange};
use crate::rulecontext::*;
use crate::RuleAction;
use crate::RuleFlags;
use tsgo_ast::Kind;

/// Every token kind from `KindFirstToken` (`Unknown`) through `KindLastToken`
/// (`DeferKeyword`), in discriminant order.
///
/// Materializes Go's `for token := KindFirstToken; token <= KindLastToken`
/// iteration. Verified contiguous by the module's self-check test.
// Go: internal/format/rules.go:getAllRules (allTokens loop)
pub const ALL_TOKEN_KINDS: &[Kind] = &[
    Kind::Unknown,
    Kind::EndOfFile,
    Kind::SingleLineCommentTrivia,
    Kind::MultiLineCommentTrivia,
    Kind::NewLineTrivia,
    Kind::WhitespaceTrivia,
    Kind::ConflictMarkerTrivia,
    Kind::NonTextFileMarkerTrivia,
    Kind::NumericLiteral,
    Kind::BigIntLiteral,
    Kind::StringLiteral,
    Kind::JsxText,
    Kind::JsxTextAllWhiteSpaces,
    Kind::RegularExpressionLiteral,
    Kind::NoSubstitutionTemplateLiteral,
    Kind::TemplateHead,
    Kind::TemplateMiddle,
    Kind::TemplateTail,
    Kind::OpenBraceToken,
    Kind::CloseBraceToken,
    Kind::OpenParenToken,
    Kind::CloseParenToken,
    Kind::OpenBracketToken,
    Kind::CloseBracketToken,
    Kind::DotToken,
    Kind::DotDotDotToken,
    Kind::SemicolonToken,
    Kind::CommaToken,
    Kind::QuestionDotToken,
    Kind::LessThanToken,
    Kind::LessThanSlashToken,
    Kind::GreaterThanToken,
    Kind::LessThanEqualsToken,
    Kind::GreaterThanEqualsToken,
    Kind::EqualsEqualsToken,
    Kind::ExclamationEqualsToken,
    Kind::EqualsEqualsEqualsToken,
    Kind::ExclamationEqualsEqualsToken,
    Kind::EqualsGreaterThanToken,
    Kind::PlusToken,
    Kind::MinusToken,
    Kind::AsteriskToken,
    Kind::AsteriskAsteriskToken,
    Kind::SlashToken,
    Kind::PercentToken,
    Kind::PlusPlusToken,
    Kind::MinusMinusToken,
    Kind::LessThanLessThanToken,
    Kind::GreaterThanGreaterThanToken,
    Kind::GreaterThanGreaterThanGreaterThanToken,
    Kind::AmpersandToken,
    Kind::BarToken,
    Kind::CaretToken,
    Kind::ExclamationToken,
    Kind::TildeToken,
    Kind::AmpersandAmpersandToken,
    Kind::BarBarToken,
    Kind::QuestionToken,
    Kind::ColonToken,
    Kind::AtToken,
    Kind::QuestionQuestionToken,
    Kind::BacktickToken,
    Kind::HashToken,
    Kind::EqualsToken,
    Kind::PlusEqualsToken,
    Kind::MinusEqualsToken,
    Kind::AsteriskEqualsToken,
    Kind::AsteriskAsteriskEqualsToken,
    Kind::SlashEqualsToken,
    Kind::PercentEqualsToken,
    Kind::LessThanLessThanEqualsToken,
    Kind::GreaterThanGreaterThanEqualsToken,
    Kind::GreaterThanGreaterThanGreaterThanEqualsToken,
    Kind::AmpersandEqualsToken,
    Kind::BarEqualsToken,
    Kind::BarBarEqualsToken,
    Kind::AmpersandAmpersandEqualsToken,
    Kind::QuestionQuestionEqualsToken,
    Kind::CaretEqualsToken,
    Kind::Identifier,
    Kind::PrivateIdentifier,
    Kind::JSDocCommentTextToken,
    Kind::BreakKeyword,
    Kind::CaseKeyword,
    Kind::CatchKeyword,
    Kind::ClassKeyword,
    Kind::ConstKeyword,
    Kind::ContinueKeyword,
    Kind::DebuggerKeyword,
    Kind::DefaultKeyword,
    Kind::DeleteKeyword,
    Kind::DoKeyword,
    Kind::ElseKeyword,
    Kind::EnumKeyword,
    Kind::ExportKeyword,
    Kind::ExtendsKeyword,
    Kind::FalseKeyword,
    Kind::FinallyKeyword,
    Kind::ForKeyword,
    Kind::FunctionKeyword,
    Kind::IfKeyword,
    Kind::ImportKeyword,
    Kind::InKeyword,
    Kind::InstanceOfKeyword,
    Kind::NewKeyword,
    Kind::NullKeyword,
    Kind::ReturnKeyword,
    Kind::SuperKeyword,
    Kind::SwitchKeyword,
    Kind::ThisKeyword,
    Kind::ThrowKeyword,
    Kind::TrueKeyword,
    Kind::TryKeyword,
    Kind::TypeOfKeyword,
    Kind::VarKeyword,
    Kind::VoidKeyword,
    Kind::WhileKeyword,
    Kind::WithKeyword,
    Kind::ImplementsKeyword,
    Kind::InterfaceKeyword,
    Kind::LetKeyword,
    Kind::PackageKeyword,
    Kind::PrivateKeyword,
    Kind::ProtectedKeyword,
    Kind::PublicKeyword,
    Kind::StaticKeyword,
    Kind::YieldKeyword,
    Kind::AbstractKeyword,
    Kind::AccessorKeyword,
    Kind::AsKeyword,
    Kind::AssertsKeyword,
    Kind::AssertKeyword,
    Kind::AnyKeyword,
    Kind::AsyncKeyword,
    Kind::AwaitKeyword,
    Kind::BooleanKeyword,
    Kind::ConstructorKeyword,
    Kind::DeclareKeyword,
    Kind::GetKeyword,
    Kind::ImmediateKeyword,
    Kind::InferKeyword,
    Kind::IntrinsicKeyword,
    Kind::IsKeyword,
    Kind::KeyOfKeyword,
    Kind::ModuleKeyword,
    Kind::NamespaceKeyword,
    Kind::NeverKeyword,
    Kind::OutKeyword,
    Kind::ReadonlyKeyword,
    Kind::RequireKeyword,
    Kind::NumberKeyword,
    Kind::ObjectKeyword,
    Kind::SatisfiesKeyword,
    Kind::SetKeyword,
    Kind::StringKeyword,
    Kind::SymbolKeyword,
    Kind::TypeKeyword,
    Kind::UndefinedKeyword,
    Kind::UniqueKeyword,
    Kind::UnknownKeyword,
    Kind::UsingKeyword,
    Kind::FromKeyword,
    Kind::GlobalKeyword,
    Kind::BigIntKeyword,
    Kind::OverrideKeyword,
    Kind::OfKeyword,
    Kind::DeferKeyword,
];

/// Builds a *specific* [`TokenRange`] from a fixed set of token kinds.
///
/// # Examples
/// ```
/// use tsgo_format::rules::token_range_from;
/// use tsgo_ast::Kind;
/// let tr = token_range_from(&[Kind::Identifier]);
/// assert!(tr.is_specific);
/// ```
///
/// Side effects: none (pure).
// Go: internal/format/rules.go:tokenRangeFrom
pub fn token_range_from(tokens: &[Kind]) -> TokenRange {
    TokenRange {
        is_specific: true,
        tokens: tokens.to_vec(),
    }
}

/// Builds a *specific* [`TokenRange`] from a `prefix` followed by extra tokens.
///
/// Mirrors Go's `tokenRangeFromEx`.
///
/// # Examples
/// ```
/// use tsgo_format::rules::token_range_from_ex;
/// use tsgo_ast::Kind;
/// let tr = token_range_from_ex(&[Kind::Identifier], &[Kind::MultiLineCommentTrivia]);
/// assert_eq!(tr.tokens.len(), 2);
/// ```
///
/// Side effects: none (pure).
// Go: internal/format/rules.go:tokenRangeFromEx
pub fn token_range_from_ex(prefix: &[Kind], tokens: &[Kind]) -> TokenRange {
    let mut combined = prefix.to_vec();
    combined.extend_from_slice(tokens);
    TokenRange {
        is_specific: true,
        tokens: combined,
    }
}

/// Builds a *specific* [`TokenRange`] covering all token kinds from `start`
/// through `end` inclusive (discriminant order).
///
/// # Examples
/// ```
/// use tsgo_format::rules::token_range_from_range;
/// use tsgo_ast::Kind;
/// let kw = token_range_from_range(Kind::FIRST_KEYWORD, Kind::LAST_KEYWORD);
/// assert_eq!(*kw.tokens.first().unwrap(), Kind::FIRST_KEYWORD);
/// ```
///
/// Side effects: none (pure).
// Go: internal/format/rules.go:tokenRangeFromRange
pub fn token_range_from_range(start: Kind, end: Kind) -> TokenRange {
    let tokens: Vec<Kind> = ALL_TOKEN_KINDS
        .iter()
        .copied()
        .filter(|k| *k >= start && *k <= end)
        .collect();
    token_range_from(&tokens)
}

/// Wraps a predicate function/closure into a boxed [`ContextPredicate`].
fn p<F: Fn(&FormattingContext) -> bool + Send + Sync + 'static>(f: F) -> ContextPredicate {
    Box::new(f)
}

/// Returns the complete, ordered list of formatting rule specs.
///
/// Order is significant: high-priority common rules first, then
/// user-configurable rules, then low-priority common rules. The rules-map
/// builder ([`crate::rulesmap::build_rules_map`]) consumes this order to assign
/// bucket priorities.
///
/// # Examples
/// ```
/// use tsgo_format::rules::get_all_rules;
/// let rules = get_all_rules();
/// assert!(rules.iter().any(|r| r.rule.name() == "SpaceAfterComma"));
/// ```
///
/// Side effects: none (pure).
// Go: internal/format/rules.go:getAllRules
pub fn get_all_rules() -> Vec<RuleSpec> {
    let all_tokens: Vec<Kind> = ALL_TOKEN_KINDS
        .iter()
        .copied()
        .filter(|k| *k != Kind::EndOfFile)
        .collect();

    let any_token_except = |exclude: &[Kind]| -> TokenRange {
        TokenRange {
            is_specific: false,
            tokens: all_tokens
                .iter()
                .copied()
                .filter(|k| !exclude.contains(k))
                .collect(),
        }
    };

    let any_token = TokenRange {
        is_specific: false,
        tokens: all_tokens.clone(),
    };

    let any_token_including_multiline_comments =
        token_range_from_ex(&all_tokens, &[Kind::MultiLineCommentTrivia]);
    let any_token_including_eof = token_range_from_ex(&all_tokens, &[Kind::EndOfFile]);
    let keywords = token_range_from_range(Kind::FIRST_KEYWORD, Kind::LAST_KEYWORD);
    let binary_operators =
        token_range_from_range(Kind::FIRST_BINARY_OPERATOR, Kind::LAST_BINARY_OPERATOR);
    let binary_keyword_operators = vec![
        Kind::InKeyword,
        Kind::InstanceOfKeyword,
        Kind::OfKeyword,
        Kind::AsKeyword,
        Kind::IsKeyword,
        Kind::SatisfiesKeyword,
    ];
    let unary_prefix_operators = vec![
        Kind::PlusPlusToken,
        Kind::MinusToken,
        Kind::TildeToken,
        Kind::ExclamationToken,
    ];
    let unary_prefix_expressions = vec![
        Kind::NumericLiteral,
        Kind::BigIntLiteral,
        Kind::Identifier,
        Kind::OpenParenToken,
        Kind::OpenBracketToken,
        Kind::OpenBraceToken,
        Kind::ThisKeyword,
        Kind::NewKeyword,
    ];
    let unary_preincrement_expressions = vec![
        Kind::Identifier,
        Kind::OpenParenToken,
        Kind::ThisKeyword,
        Kind::NewKeyword,
    ];
    let unary_postincrement_expressions = vec![
        Kind::Identifier,
        Kind::CloseParenToken,
        Kind::CloseBracketToken,
        Kind::NewKeyword,
    ];
    let unary_predecrement_expressions = vec![
        Kind::Identifier,
        Kind::OpenParenToken,
        Kind::ThisKeyword,
        Kind::NewKeyword,
    ];
    let unary_postdecrement_expressions = vec![
        Kind::Identifier,
        Kind::CloseParenToken,
        Kind::CloseBracketToken,
        Kind::NewKeyword,
    ];
    let comments = vec![Kind::SingleLineCommentTrivia, Kind::MultiLineCommentTrivia];
    let type_keywords = vec![
        Kind::AnyKeyword,
        Kind::AssertsKeyword,
        Kind::BigIntKeyword,
        Kind::BooleanKeyword,
        Kind::FalseKeyword,
        Kind::InferKeyword,
        Kind::KeyOfKeyword,
        Kind::NeverKeyword,
        Kind::NullKeyword,
        Kind::NumberKeyword,
        Kind::ObjectKeyword,
        Kind::ReadonlyKeyword,
        Kind::StringKeyword,
        Kind::SymbolKeyword,
        Kind::TypeOfKeyword,
        Kind::TrueKeyword,
        Kind::VoidKeyword,
        Kind::UndefinedKeyword,
        Kind::UniqueKeyword,
        Kind::UnknownKeyword,
    ];
    let mut type_names = vec![Kind::Identifier];
    type_names.extend_from_slice(&type_keywords);

    // Place a space before open brace in a function declaration.
    let function_open_brace_left_token_range = any_token_including_multiline_comments.clone();
    // Place a space before open brace in a TS decl with braces as children.
    let typescript_open_brace_left_token_range = token_range_from(&[
        Kind::Identifier,
        Kind::GreaterThanToken,
        Kind::MultiLineCommentTrivia,
        Kind::ClassKeyword,
        Kind::ExportKeyword,
        Kind::ImportKeyword,
    ]);
    // Place a space before open brace in a control-flow construct.
    let control_open_brace_left_token_range = token_range_from(&[
        Kind::CloseParenToken,
        Kind::MultiLineCommentTrivia,
        Kind::DoKeyword,
        Kind::TryKeyword,
        Kind::FinallyKeyword,
        Kind::ElseKeyword,
        Kind::CatchKeyword,
    ]);

    // These rules are higher in priority than user-configurable.
    let high_priority_common_rules: Vec<RuleSpec> = vec![
        rule(
            "IgnoreBeforeComment",
            any_token.clone(),
            comments.clone(),
            any_context(),
            RuleAction::STOP_PROCESSING_SPACE_ACTIONS,
        ),
        rule(
            "IgnoreAfterLineComment",
            Kind::SingleLineCommentTrivia,
            any_token.clone(),
            any_context(),
            RuleAction::STOP_PROCESSING_SPACE_ACTIONS,
        ),
        rule(
            "NotSpaceBeforeColon",
            any_token.clone(),
            Kind::ColonToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_binary_op_context),
                p(is_not_type_annotation_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterColon",
            Kind::ColonToken,
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_binary_op_context),
                p(is_next_token_parent_not_jsx_namespaced_name),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeQuestionMark",
            any_token.clone(),
            Kind::QuestionToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_binary_op_context),
                p(is_not_type_annotation_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterQuestionMarkInConditionalOperator",
            Kind::QuestionToken,
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_conditional_operator_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterQuestionMark",
            Kind::QuestionToken,
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_non_optional_property_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeDot",
            any_token.clone(),
            vec![Kind::DotToken, Kind::QuestionDotToken],
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_property_access_on_integer_literal),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterDot",
            vec![Kind::DotToken, Kind::QuestionDotToken],
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBetweenImportParenInImportType",
            Kind::ImportKeyword,
            Kind::OpenParenToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_import_type_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterUnaryPrefixOperator",
            unary_prefix_operators.clone(),
            unary_prefix_expressions.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_binary_op_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterUnaryPreincrementOperator",
            Kind::PlusPlusToken,
            unary_preincrement_expressions.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterUnaryPredecrementOperator",
            Kind::MinusMinusToken,
            unary_predecrement_expressions.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeUnaryPostincrementOperator",
            unary_postincrement_expressions.clone(),
            Kind::PlusPlusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_statement_condition_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeUnaryPostdecrementOperator",
            unary_postdecrement_expressions.clone(),
            Kind::MinusMinusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_statement_condition_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterPostincrementWhenFollowedByAdd",
            Kind::PlusPlusToken,
            Kind::PlusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterAddWhenFollowedByUnaryPlus",
            Kind::PlusToken,
            Kind::PlusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterAddWhenFollowedByPreincrement",
            Kind::PlusToken,
            Kind::PlusPlusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterPostdecrementWhenFollowedBySubtract",
            Kind::MinusMinusToken,
            Kind::MinusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterSubtractWhenFollowedByUnaryMinus",
            Kind::MinusToken,
            Kind::MinusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterSubtractWhenFollowedByPredecrement",
            Kind::MinusToken,
            Kind::MinusMinusToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterCloseBrace",
            Kind::CloseBraceToken,
            vec![Kind::CommaToken, Kind::SemicolonToken],
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NewLineBeforeCloseBraceInBlockContext",
            any_token_including_multiline_comments.clone(),
            Kind::CloseBraceToken,
            vec![p(is_multiline_block_context)],
            RuleAction::INSERT_NEW_LINE,
        ),
        rule(
            "SpaceAfterCloseBrace",
            Kind::CloseBraceToken,
            any_token_except(&[Kind::CloseParenToken]),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_after_code_block_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenCloseBraceAndElse",
            Kind::CloseBraceToken,
            Kind::ElseKeyword,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenCloseBraceAndWhile",
            Kind::CloseBraceToken,
            Kind::WhileKeyword,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenEmptyBraceBrackets",
            Kind::OpenBraceToken,
            Kind::CloseBraceToken,
            vec![p(is_non_jsx_same_line_token_context), p(is_object_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterConditionalClosingParen",
            Kind::CloseParenToken,
            Kind::OpenBracketToken,
            vec![p(is_control_decl_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenFunctionKeywordAndStar",
            Kind::FunctionKeyword,
            Kind::AsteriskToken,
            vec![p(is_function_declaration_or_function_expression_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterStarInGeneratorDeclaration",
            Kind::AsteriskToken,
            Kind::Identifier,
            vec![p(is_function_declaration_or_function_expression_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterFunctionInFuncDecl",
            Kind::FunctionKeyword,
            any_token.clone(),
            vec![p(is_function_decl_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NewLineAfterOpenBraceInBlockContext",
            Kind::OpenBraceToken,
            any_token.clone(),
            vec![p(is_multiline_block_context)],
            RuleAction::INSERT_NEW_LINE,
        ),
        rule(
            "SpaceAfterGetSetInMember",
            vec![Kind::GetKeyword, Kind::SetKeyword],
            Kind::Identifier,
            vec![p(is_function_decl_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenYieldKeywordAndStar",
            Kind::YieldKeyword,
            Kind::AsteriskToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_yield_or_yield_star_with_operand),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBetweenYieldOrYieldStarAndOperand",
            vec![Kind::YieldKeyword, Kind::AsteriskToken],
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_yield_or_yield_star_with_operand),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenReturnAndSemicolon",
            Kind::ReturnKeyword,
            Kind::SemicolonToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterCertainKeywords",
            vec![
                Kind::VarKeyword,
                Kind::ThrowKeyword,
                Kind::NewKeyword,
                Kind::DeleteKeyword,
                Kind::ReturnKeyword,
                Kind::TypeOfKeyword,
                Kind::AwaitKeyword,
            ],
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterLetConstInVariableDeclaration",
            vec![Kind::LetKeyword, Kind::ConstKeyword],
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_start_of_variable_declaration_list),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeOpenParenInFuncCall",
            any_token.clone(),
            Kind::OpenParenToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_function_call_or_new_context),
                p(is_previous_token_not_comma),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBeforeBinaryKeywordOperator",
            any_token.clone(),
            binary_keyword_operators.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterBinaryKeywordOperator",
            binary_keyword_operators.clone(),
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterVoidOperator",
            Kind::VoidKeyword,
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context), p(is_void_op_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenAsyncAndOpenParen",
            Kind::AsyncKeyword,
            Kind::OpenParenToken,
            vec![
                p(is_arrow_function_context),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenAsyncAndFunctionKeyword",
            Kind::AsyncKeyword,
            vec![Kind::FunctionKeyword, Kind::Identifier],
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenTagAndTemplateString",
            vec![Kind::Identifier, Kind::CloseParenToken],
            vec![Kind::NoSubstitutionTemplateLiteral, Kind::TemplateHead],
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBeforeJsxAttribute",
            any_token.clone(),
            Kind::Identifier,
            vec![
                p(is_next_token_parent_jsx_attribute),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeSlashInJsxOpeningElement",
            any_token.clone(),
            Kind::SlashToken,
            vec![
                p(is_jsx_self_closing_element_context),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeGreaterThanTokenInJsxOpeningElement",
            Kind::SlashToken,
            Kind::GreaterThanToken,
            vec![
                p(is_jsx_self_closing_element_context),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeEqualInJsxAttribute",
            any_token.clone(),
            Kind::EqualsToken,
            vec![
                p(is_jsx_attribute_context),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterEqualInJsxAttribute",
            Kind::EqualsToken,
            any_token.clone(),
            vec![
                p(is_jsx_attribute_context),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeJsxNamespaceColon",
            Kind::Identifier,
            Kind::ColonToken,
            vec![p(is_next_token_parent_jsx_namespaced_name)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterJsxNamespaceColon",
            Kind::ColonToken,
            Kind::Identifier,
            vec![p(is_next_token_parent_jsx_namespaced_name)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterModuleImport",
            vec![Kind::ModuleKeyword, Kind::RequireKeyword],
            Kind::OpenParenToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterCertainTypeScriptKeywords",
            vec![
                Kind::AbstractKeyword,
                Kind::AccessorKeyword,
                Kind::ClassKeyword,
                Kind::DeclareKeyword,
                Kind::DefaultKeyword,
                Kind::EnumKeyword,
                Kind::ExportKeyword,
                Kind::ExtendsKeyword,
                Kind::GetKeyword,
                Kind::ImplementsKeyword,
                Kind::ImportKeyword,
                Kind::InterfaceKeyword,
                Kind::ModuleKeyword,
                Kind::NamespaceKeyword,
                Kind::OverrideKeyword,
                Kind::PrivateKeyword,
                Kind::PublicKeyword,
                Kind::ProtectedKeyword,
                Kind::ReadonlyKeyword,
                Kind::SetKeyword,
                Kind::StaticKeyword,
                Kind::TypeKeyword,
                Kind::FromKeyword,
                Kind::KeyOfKeyword,
                Kind::InferKeyword,
            ],
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeCertainTypeScriptKeywords",
            any_token.clone(),
            vec![
                Kind::ExtendsKeyword,
                Kind::ImplementsKeyword,
                Kind::FromKeyword,
            ],
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterModuleName",
            Kind::StringLiteral,
            Kind::OpenBraceToken,
            vec![p(is_module_decl_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeArrow",
            any_token.clone(),
            Kind::EqualsGreaterThanToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterArrow",
            Kind::EqualsGreaterThanToken,
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterEllipsis",
            Kind::DotDotDotToken,
            Kind::Identifier,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterOptionalParameters",
            Kind::QuestionToken,
            vec![Kind::CloseParenToken, Kind::CommaToken],
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_binary_op_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBetweenEmptyInterfaceBraceBrackets",
            Kind::OpenBraceToken,
            Kind::CloseBraceToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_object_type_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeOpenAngularBracket",
            type_names.clone(),
            Kind::LessThanToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_type_argument_or_parameter_or_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBetweenCloseParenAndAngularBracket",
            Kind::CloseParenToken,
            Kind::LessThanToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_type_argument_or_parameter_or_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterOpenAngularBracket",
            Kind::LessThanToken,
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_type_argument_or_parameter_or_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeCloseAngularBracket",
            any_token.clone(),
            Kind::GreaterThanToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_type_argument_or_parameter_or_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterCloseAngularBracket",
            Kind::GreaterThanToken,
            vec![
                Kind::OpenParenToken,
                Kind::OpenBracketToken,
                Kind::GreaterThanToken,
                Kind::CommaToken,
            ],
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_type_argument_or_parameter_or_assertion_context),
                p(is_not_function_decl_context),
                p(is_non_type_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBeforeAt",
            vec![Kind::CloseParenToken, Kind::Identifier],
            Kind::AtToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterAt",
            Kind::AtToken,
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterDecorator",
            any_token.clone(),
            vec![
                Kind::AbstractKeyword,
                Kind::Identifier,
                Kind::ExportKeyword,
                Kind::DefaultKeyword,
                Kind::ClassKeyword,
                Kind::StaticKeyword,
                Kind::PublicKeyword,
                Kind::PrivateKeyword,
                Kind::ProtectedKeyword,
                Kind::GetKeyword,
                Kind::SetKeyword,
                Kind::OpenBracketToken,
                Kind::AsteriskToken,
            ],
            vec![p(is_end_of_decorator_context_on_same_line)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeNonNullAssertionOperator",
            any_token.clone(),
            Kind::ExclamationToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_non_null_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterNewKeywordOnConstructorSignature",
            Kind::NewKeyword,
            Kind::OpenParenToken,
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_constructor_signature_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceLessThanAndNonJSXTypeAnnotation",
            Kind::LessThanToken,
            Kind::LessThanToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
    ];

    // These rules are applied after high priority.
    let user_configurable_rules: Vec<RuleSpec> = vec![
        rule(
            "SpaceAfterConstructor",
            Kind::ConstructorKeyword,
            Kind::OpenParenToken,
            vec![
                is_option_enabled(insert_space_after_constructor_option),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterConstructor",
            Kind::ConstructorKeyword,
            Kind::OpenParenToken,
            vec![
                is_option_disabled_or_undefined(insert_space_after_constructor_option),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterComma",
            Kind::CommaToken,
            any_token.clone(),
            vec![
                is_option_enabled(insert_space_after_comma_delimiter_option),
                p(is_non_jsx_same_line_token_context),
                p(is_non_jsx_element_or_fragment_context),
                p(is_next_token_not_close_bracket),
                p(is_next_token_not_close_paren),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterComma",
            Kind::CommaToken,
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(insert_space_after_comma_delimiter_option),
                p(is_non_jsx_same_line_token_context),
                p(is_non_jsx_element_or_fragment_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterAnonymousFunctionKeyword",
            vec![Kind::FunctionKeyword, Kind::AsteriskToken],
            Kind::OpenParenToken,
            vec![
                is_option_enabled(
                    insert_space_after_function_keyword_for_anonymous_functions_option,
                ),
                p(is_function_decl_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterAnonymousFunctionKeyword",
            vec![Kind::FunctionKeyword, Kind::AsteriskToken],
            Kind::OpenParenToken,
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_function_keyword_for_anonymous_functions_option,
                ),
                p(is_function_decl_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterKeywordInControl",
            keywords.clone(),
            Kind::OpenParenToken,
            vec![
                is_option_enabled(insert_space_after_keywords_in_control_flow_statements_option),
                p(is_control_decl_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterKeywordInControl",
            keywords.clone(),
            Kind::OpenParenToken,
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_keywords_in_control_flow_statements_option,
                ),
                p(is_control_decl_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterOpenParen",
            Kind::OpenParenToken,
            any_token.clone(),
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_nonempty_parenthesis_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeCloseParen",
            any_token.clone(),
            Kind::CloseParenToken,
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_nonempty_parenthesis_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenOpenParens",
            Kind::OpenParenToken,
            Kind::OpenParenToken,
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_nonempty_parenthesis_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenParens",
            Kind::OpenParenToken,
            Kind::CloseParenToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterOpenParen",
            Kind::OpenParenToken,
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_nonempty_parenthesis_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeCloseParen",
            any_token.clone(),
            Kind::CloseParenToken,
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_nonempty_parenthesis_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterOpenBracket",
            Kind::OpenBracketToken,
            any_token.clone(),
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_nonempty_brackets_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeCloseBracket",
            any_token.clone(),
            Kind::CloseBracketToken,
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_nonempty_brackets_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenBrackets",
            Kind::OpenBracketToken,
            Kind::CloseBracketToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterOpenBracket",
            Kind::OpenBracketToken,
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_nonempty_brackets_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeCloseBracket",
            any_token.clone(),
            Kind::CloseBracketToken,
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_nonempty_brackets_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterOpenBrace",
            Kind::OpenBraceToken,
            any_token.clone(),
            vec![
                is_option_enabled_or_undefined(
                    insert_space_after_opening_and_before_closing_nonempty_braces_option,
                ),
                p(is_brace_wrapped_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeCloseBrace",
            any_token.clone(),
            Kind::CloseBraceToken,
            vec![
                is_option_enabled_or_undefined(
                    insert_space_after_opening_and_before_closing_nonempty_braces_option,
                ),
                p(is_brace_wrapped_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenEmptyBraceBrackets",
            Kind::OpenBraceToken,
            Kind::CloseBraceToken,
            vec![p(is_non_jsx_same_line_token_context), p(is_object_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterOpenBrace",
            Kind::OpenBraceToken,
            any_token.clone(),
            vec![
                is_option_disabled(
                    insert_space_after_opening_and_before_closing_nonempty_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeCloseBrace",
            any_token.clone(),
            Kind::CloseBraceToken,
            vec![
                is_option_disabled(
                    insert_space_after_opening_and_before_closing_nonempty_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBetweenEmptyBraceBrackets",
            Kind::OpenBraceToken,
            Kind::CloseBraceToken,
            vec![is_option_enabled(
                insert_space_after_opening_and_before_closing_empty_braces_option,
            )],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBetweenEmptyBraceBrackets",
            Kind::OpenBraceToken,
            Kind::CloseBraceToken,
            vec![
                is_option_disabled(
                    insert_space_after_opening_and_before_closing_empty_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule_flags(
            "SpaceAfterTemplateHeadAndMiddle",
            vec![Kind::TemplateHead, Kind::TemplateMiddle],
            any_token.clone(),
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_template_string_braces_option,
                ),
                p(is_non_jsx_text_context),
            ],
            RuleAction::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "SpaceBeforeTemplateMiddleAndTail",
            any_token.clone(),
            vec![Kind::TemplateMiddle, Kind::TemplateTail],
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_template_string_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule_flags(
            "NoSpaceAfterTemplateHeadAndMiddle",
            vec![Kind::TemplateHead, Kind::TemplateMiddle],
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_template_string_braces_option,
                ),
                p(is_non_jsx_text_context),
            ],
            RuleAction::DELETE_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "NoSpaceBeforeTemplateMiddleAndTail",
            any_token.clone(),
            vec![Kind::TemplateMiddle, Kind::TemplateTail],
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_template_string_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterOpenBraceInJsxExpression",
            Kind::OpenBraceToken,
            any_token.clone(),
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_jsx_expression_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_jsx_expression_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBeforeCloseBraceInJsxExpression",
            any_token.clone(),
            Kind::CloseBraceToken,
            vec![
                is_option_enabled(
                    insert_space_after_opening_and_before_closing_jsx_expression_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_jsx_expression_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterOpenBraceInJsxExpression",
            Kind::OpenBraceToken,
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_jsx_expression_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_jsx_expression_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeCloseBraceInJsxExpression",
            any_token.clone(),
            Kind::CloseBraceToken,
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_opening_and_before_closing_jsx_expression_braces_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_jsx_expression_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterSemicolonInFor",
            Kind::SemicolonToken,
            any_token.clone(),
            vec![
                is_option_enabled(insert_space_after_semicolon_in_for_statements_option),
                p(is_non_jsx_same_line_token_context),
                p(is_for_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterSemicolonInFor",
            Kind::SemicolonToken,
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_after_semicolon_in_for_statements_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_for_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBeforeBinaryOperator",
            any_token.clone(),
            binary_operators.clone(),
            vec![
                is_option_enabled(insert_space_before_and_after_binary_operators_option),
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterBinaryOperator",
            binary_operators.clone(),
            any_token.clone(),
            vec![
                is_option_enabled(insert_space_before_and_after_binary_operators_option),
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeBinaryOperator",
            any_token.clone(),
            binary_operators.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_before_and_after_binary_operators_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterBinaryOperator",
            binary_operators.clone(),
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(
                    insert_space_before_and_after_binary_operators_option,
                ),
                p(is_non_jsx_same_line_token_context),
                p(is_binary_op_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBeforeOpenParenInFuncDecl",
            any_token.clone(),
            Kind::OpenParenToken,
            vec![
                is_option_enabled(insert_space_before_function_parenthesis_option),
                p(is_non_jsx_same_line_token_context),
                p(is_function_decl_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeOpenParenInFuncDecl",
            any_token.clone(),
            Kind::OpenParenToken,
            vec![
                is_option_disabled_or_undefined(insert_space_before_function_parenthesis_option),
                p(is_non_jsx_same_line_token_context),
                p(is_function_decl_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule_flags(
            "NewLineBeforeOpenBraceInControl",
            control_open_brace_left_token_range.clone(),
            Kind::OpenBraceToken,
            vec![
                is_option_enabled(place_open_brace_on_new_line_for_control_blocks_option),
                p(is_control_decl_context),
                p(is_before_multiline_block_context),
            ],
            RuleAction::INSERT_NEW_LINE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule_flags(
            "NewLineBeforeOpenBraceInFunction",
            function_open_brace_left_token_range.clone(),
            Kind::OpenBraceToken,
            vec![
                is_option_enabled(place_open_brace_on_new_line_for_functions_option),
                p(is_function_decl_context),
                p(is_before_multiline_block_context),
            ],
            RuleAction::INSERT_NEW_LINE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule_flags(
            "NewLineBeforeOpenBraceInTypeScriptDeclWithBlock",
            typescript_open_brace_left_token_range.clone(),
            Kind::OpenBraceToken,
            vec![
                is_option_enabled(place_open_brace_on_new_line_for_functions_option),
                p(is_typescript_decl_with_block_context),
                p(is_before_multiline_block_context),
            ],
            RuleAction::INSERT_NEW_LINE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "SpaceAfterTypeAssertion",
            Kind::GreaterThanToken,
            any_token.clone(),
            vec![
                is_option_enabled(insert_space_after_type_assertion_option),
                p(is_non_jsx_same_line_token_context),
                p(is_type_assertion_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceAfterTypeAssertion",
            Kind::GreaterThanToken,
            any_token.clone(),
            vec![
                is_option_disabled_or_undefined(insert_space_after_type_assertion_option),
                p(is_non_jsx_same_line_token_context),
                p(is_type_assertion_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBeforeTypeAnnotation",
            any_token.clone(),
            vec![Kind::QuestionToken, Kind::ColonToken],
            vec![
                is_option_enabled(insert_space_before_type_annotation_option),
                p(is_non_jsx_same_line_token_context),
                p(is_type_annotation_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "NoSpaceBeforeTypeAnnotation",
            any_token.clone(),
            vec![Kind::QuestionToken, Kind::ColonToken],
            vec![
                is_option_disabled_or_undefined(insert_space_before_type_annotation_option),
                p(is_non_jsx_same_line_token_context),
                p(is_type_annotation_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoOptionalSemicolon",
            Kind::SemicolonToken,
            any_token_including_eof.clone(),
            vec![
                option_equals(semicolon_option, crate::SemicolonPreference::Remove),
                p(is_semicolon_deletion_context),
            ],
            RuleAction::DELETE_TOKEN,
        ),
        rule(
            "OptionalSemicolon",
            any_token.clone(),
            any_token_including_eof.clone(),
            vec![
                option_equals(semicolon_option, crate::SemicolonPreference::Insert),
                p(is_semicolon_insertion_context),
            ],
            RuleAction::INSERT_TRAILING_SEMICOLON,
        ),
    ];

    // These rules are lower in priority than user-configurable.
    let low_priority_common_rules: Vec<RuleSpec> = vec![
        rule(
            "NoSpaceBeforeSemicolon",
            any_token.clone(),
            Kind::SemicolonToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule_flags(
            "SpaceBeforeOpenBraceInControl",
            control_open_brace_left_token_range.clone(),
            Kind::OpenBraceToken,
            vec![
                is_option_disabled_or_undefined_or_tokens_on_same_line(
                    place_open_brace_on_new_line_for_control_blocks_option,
                ),
                p(is_control_decl_context),
                p(is_not_format_on_enter),
                p(is_same_line_token_or_before_block_context),
            ],
            RuleAction::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule_flags(
            "SpaceBeforeOpenBraceInFunction",
            function_open_brace_left_token_range.clone(),
            Kind::OpenBraceToken,
            vec![
                is_option_disabled_or_undefined_or_tokens_on_same_line(
                    place_open_brace_on_new_line_for_functions_option,
                ),
                p(is_function_decl_context),
                p(is_before_block_context),
                p(is_not_format_on_enter),
                p(is_same_line_token_or_before_block_context),
            ],
            RuleAction::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule_flags(
            "SpaceBeforeOpenBraceInTypeScriptDeclWithBlock",
            typescript_open_brace_left_token_range.clone(),
            Kind::OpenBraceToken,
            vec![
                is_option_disabled_or_undefined_or_tokens_on_same_line(
                    place_open_brace_on_new_line_for_functions_option,
                ),
                p(is_typescript_decl_with_block_context),
                p(is_not_format_on_enter),
                p(is_same_line_token_or_before_block_context),
            ],
            RuleAction::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "NoSpaceBeforeComma",
            any_token.clone(),
            Kind::CommaToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceBeforeOpenBracket",
            any_token_except(&[Kind::AsyncKeyword, Kind::CaseKeyword]),
            Kind::OpenBracketToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "NoSpaceAfterCloseBracket",
            Kind::CloseBracketToken,
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_not_before_block_in_function_declaration_context),
            ],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceAfterSemicolon",
            Kind::SemicolonToken,
            any_token.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenForAndAwaitKeyword",
            Kind::ForKeyword,
            Kind::AwaitKeyword,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceBetweenDotDotDotAndTypeName",
            Kind::DotDotDotToken,
            type_names.clone(),
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::DELETE_SPACE,
        ),
        rule(
            "SpaceBetweenStatements",
            vec![
                Kind::CloseParenToken,
                Kind::DoKeyword,
                Kind::ElseKeyword,
                Kind::CaseKeyword,
            ],
            any_token.clone(),
            vec![
                p(is_non_jsx_same_line_token_context),
                p(is_non_jsx_element_or_fragment_context),
                p(is_not_for_context),
            ],
            RuleAction::INSERT_SPACE,
        ),
        rule(
            "SpaceAfterTryCatchFinally",
            vec![Kind::TryKeyword, Kind::CatchKeyword, Kind::FinallyKeyword],
            Kind::OpenBraceToken,
            vec![p(is_non_jsx_same_line_token_context)],
            RuleAction::INSERT_SPACE,
        ),
    ];

    let mut result = Vec::with_capacity(
        high_priority_common_rules.len()
            + user_configurable_rules.len()
            + low_priority_common_rules.len(),
    );
    result.extend(high_priority_common_rules);
    result.extend(user_configurable_rules);
    result.extend(low_priority_common_rules);
    result
}

#[cfg(test)]
#[path = "rules_test.rs"]
mod tests;
