// Code generated by generate.go; DO NOT EDIT.

//! Embedded localized diagnostic messages and the locale matcher table.
//!
//! 1:1 port of Go `internal/diagnostics/loc_generated.go`. The 13 translation
//! files in this directory are gzip-compressed JSON objects (`{key: text}`),
//! embedded with [`include_bytes!`] and lazily decompressed once per language
//! (mirroring Go's `//go:embed` + `sync.OnceValue`).

use std::sync::OnceLock;

use rustc_hash::FxHashMap;

/// Per-locale translation table: diagnostic key -> translated text.
pub(crate) type LocaleMessages = FxHashMap<String, String>;

type Loader = fn() -> &'static LocaleMessages;

/// Tags understood by the matcher, in the same order as Go's
/// `language.NewMatcher`. English is index 0 (the default; no translation).
// Go: internal/diagnostics/loc_generated.go:matcher
pub(crate) static MATCHER_TAGS: &[&str] = &[
    "en", "zh-CN", "zh-TW", "cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "ja-JP", "ko-KR", "pl-PL",
    "pt-BR", "ru-RU", "tr-TR",
];

/// Loader for each matcher tag (index-aligned with [`MATCHER_TAGS`]). Index 0
/// (English) is `None` since the default English text is used directly.
// Go: internal/diagnostics/loc_generated.go:localeFuncs
pub(crate) static LOCALE_FUNCS: &[Option<Loader>] = &[
    None,
    Some(zh_cn),
    Some(zh_tw),
    Some(cs_cz),
    Some(de_de),
    Some(es_es),
    Some(fr_fr),
    Some(it_it),
    Some(ja_jp),
    Some(ko_kr),
    Some(pl_pl),
    Some(pt_br),
    Some(ru_ru),
    Some(tr_tr),
];

/// Decompresses gzip-encoded JSON locale data into a [`LocaleMessages`] map.
///
/// Panics if the bytes are not valid gzip or not a JSON object of
/// string->string, mirroring Go's `loadLocaleData`.
// Go: internal/diagnostics/loc_generated.go:loadLocaleData
fn load_locale_data(data: &[u8]) -> LocaleMessages {
    let reader = flate2::read::GzDecoder::new(data);
    tsgo_json::unmarshal_read(reader).expect("failed to unmarshal locale data")
}

static ZH_CN_DATA: &[u8] = include_bytes!("zh-CN.json.gz");
static ZH_CN: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:zhCN
fn zh_cn() -> &'static LocaleMessages {
    ZH_CN.get_or_init(|| load_locale_data(ZH_CN_DATA))
}

static ZH_TW_DATA: &[u8] = include_bytes!("zh-TW.json.gz");
static ZH_TW: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:zhTW
fn zh_tw() -> &'static LocaleMessages {
    ZH_TW.get_or_init(|| load_locale_data(ZH_TW_DATA))
}

static CS_CZ_DATA: &[u8] = include_bytes!("cs-CZ.json.gz");
static CS_CZ: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:csCZ
fn cs_cz() -> &'static LocaleMessages {
    CS_CZ.get_or_init(|| load_locale_data(CS_CZ_DATA))
}

static DE_DE_DATA: &[u8] = include_bytes!("de-DE.json.gz");
static DE_DE: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:deDE
fn de_de() -> &'static LocaleMessages {
    DE_DE.get_or_init(|| load_locale_data(DE_DE_DATA))
}

static ES_ES_DATA: &[u8] = include_bytes!("es-ES.json.gz");
static ES_ES: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:esES
fn es_es() -> &'static LocaleMessages {
    ES_ES.get_or_init(|| load_locale_data(ES_ES_DATA))
}

static FR_FR_DATA: &[u8] = include_bytes!("fr-FR.json.gz");
static FR_FR: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:frFR
fn fr_fr() -> &'static LocaleMessages {
    FR_FR.get_or_init(|| load_locale_data(FR_FR_DATA))
}

static IT_IT_DATA: &[u8] = include_bytes!("it-IT.json.gz");
static IT_IT: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:itIT
fn it_it() -> &'static LocaleMessages {
    IT_IT.get_or_init(|| load_locale_data(IT_IT_DATA))
}

static JA_JP_DATA: &[u8] = include_bytes!("ja-JP.json.gz");
static JA_JP: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:jaJP
fn ja_jp() -> &'static LocaleMessages {
    JA_JP.get_or_init(|| load_locale_data(JA_JP_DATA))
}

static KO_KR_DATA: &[u8] = include_bytes!("ko-KR.json.gz");
static KO_KR: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:koKR
fn ko_kr() -> &'static LocaleMessages {
    KO_KR.get_or_init(|| load_locale_data(KO_KR_DATA))
}

static PL_PL_DATA: &[u8] = include_bytes!("pl-PL.json.gz");
static PL_PL: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:plPL
fn pl_pl() -> &'static LocaleMessages {
    PL_PL.get_or_init(|| load_locale_data(PL_PL_DATA))
}

static PT_BR_DATA: &[u8] = include_bytes!("pt-BR.json.gz");
static PT_BR: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:ptBR
fn pt_br() -> &'static LocaleMessages {
    PT_BR.get_or_init(|| load_locale_data(PT_BR_DATA))
}

static RU_RU_DATA: &[u8] = include_bytes!("ru-RU.json.gz");
static RU_RU: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:ruRU
fn ru_ru() -> &'static LocaleMessages {
    RU_RU.get_or_init(|| load_locale_data(RU_RU_DATA))
}

static TR_TR_DATA: &[u8] = include_bytes!("tr-TR.json.gz");
static TR_TR: OnceLock<LocaleMessages> = OnceLock::new();
// Go: internal/diagnostics/loc_generated.go:trTR
fn tr_tr() -> &'static LocaleMessages {
    TR_TR.get_or_init(|| load_locale_data(TR_TR_DATA))
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
